cloudfoundry/cf-deployment-concourse-tasks

- update-integration-configs/task
- update-integration-configs/task.yml
Hi,
This PR adds support for injecting the `api` and `apps_domain` values into the CATs integration config JSON file. We noticed that the apps_domain is set to the same value as the system_domain in the cf-deployment manifest (see [here](https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L28) for an example), so we didn't add support for separate domains.
> Inject the api and apps_domain if a system domain is specified

- bbl-up/task
To make these tasks more flexible, allow the load balancer certs and service account json (when GCP) to be filepaths or their contents.
> Optionally allow some parameters to be filepaths

- README.md
We copy and pasted the example and were surprised to find out that we were on a super old version.
cc @zankich
> Update the README to reflect to latest release

- dockerfiles/cf-deployment-concourse-tasks/Dockerfile
Not sure if it's retained for a reason, but it doesn't seem like it's used (and it's also an older version with some buggy behavior). Dunno; PR if useful.
> Remove bosh-init from Dockerfile

- bbl-up/task
- bbl-up/task.yml
- bosh-cleanup/task
- bosh-delete-deployment/task
- bosh-upload-stemcell-from-cf-deployment/task
- collect-ops-files/task
This accomplishes essentially the same function as PR #26 but goes about it slightly differently. In this case, the `setup_bosh_env_vars` function from `shared-functions` is used in place of every inline `setup_bosh_env_vars` function definition. Some other functions have been renamed to avoid name collisions.
This is needed to implement support for jumpboxes in the BBL pipeline since `eval "$(bbl print-env)"` now also starts up the ssh tunnel to connect to the BOSH director through the jumpbox. 
The relevant Tracker story is here: https://www.pivotaltracker.com/story/show/146740257
> Use shared-functions for all setup_bosh_env_vars calls

- bbl-destroy/task.yml
- bbl-up/task.yml
- bosh-cleanup/task.yml
- bosh-delete-deployment/task.yml
- bosh-deploy-with-created-release/task.yml
- bosh-deploy/task.yml
- bosh-upload-stemcell-from-cf-deployment/task.yml
- shared-functions
This PR contains a couple changes designed to enable using `bbl up --credhub` in CI pipelines.
The first is that, in order to prevent containers from hanging for a long time after jobs which run `eval "$(bbl print-env)"` (which opens an ssh connection when credhub is enabled), the `setup_bosh_env_vars` task in `shared_functions` kills ssh connections on exit.
The second change is due to bbl no longer persisting IAAS credentials in `bbl-state.json` when credhub is enabled. As a result, when credhub is enabled, we must pass in the IAAS credentials manually to every task which runs a bbl command (including `bbl print-env`).
/cc @mcwumbly
> Allow `bbl up --credhub` in CI pipelines

- bbl-destroy/task
- bosh-cleanup/task
- bosh-delete-deployment/task
- bosh-deploy-with-created-release/task
- bosh-deploy/task
- bosh-upload-stemcell-from-cf-deployment/task
- shared-functions
The shared function `setup_bosh_env_vars` runs `eval "$(bbl print-env)"`; when the bbl environment has a jumpbox, this will create an SSH connection to the jumpbox. The SSH connection does not close on its own, which means that Concourse will keep containers alive for an undesired period of time (around 10 minutes) after the job has actually finished.
The previous approach to this, in PR #28, used `trap pkill ssh || true` in `setup_bosh_env_vars`. This conflicted with traps for committing var-stores, so instead in this PR, we are killing ssh connections manually at the end of each task which runs `setup_bosh_env_vars`.
We have confirmed that this works both with and without a jumpbox in the BBL pipeline.
> Kill ssh connections for bbl --credhub manually

- bosh-upload-stemcell-from-cf-deployment/task
This allows this task to work with manifests that use `version: latest` for the stemcell, like [this one](https://github.com/evanfarrar/concourse-deployment/blob/ab29b5ad6d808e9126066241fdf51206099370aa/concourse-deployment.yml#L17).
> Add ability to use 'latest' stemcell version

- bbl-up/task
- bbl-up/task.yml
- If set to `true` do not create LBs
> Add IS_BOSH_LITE env var to bbl-up task

- bbl-destroy/task
- bbl-destroy/task.yml
- bbl-up/task
- bbl-up/task.yml
- bosh-delete-deployment/task.yml
- bosh-deploy-with-created-release/task.yml
- bosh-deploy/task.yml
- bosh-upload-stemcell-from-cf-deployment/task.yml
`bbl` now writes multiple files to the state directory, including terraform templates and state, vars-store files, create and delete env scripts, and manifests and ops files for the director and jumpbox. Since some of these files hold state which was formerly present in `bbl-state.json`, they should be tracked by Git as part of the user's bbl states repo.
cc: @desmondrawls @evanfarrar
> Track the entire contents of the bbl state dir

- set-feature-flags/task
- set-feature-flags/task.yml
The current set-feature-flag task only allows diego_docker + task_creation to be set. We would like to be able to enable/disable any feature flags.
This PR is an alternative design, its more a conversation starter. Thoughts?
Note: Totally not backward compatible or anything sensible like that.
> Allow dynamic list of feature flags to be enabled/disabled

- bbl-up/task
[it isn't there anymore](https://github.com/cloudfoundry/bosh-bootloader/tree/master/plan-patches/bosh-lite-gcp)
- commit that removed it: https://github.com/cloudfoundry/bosh-bootloader/commit/e7eb1d2de937c2d963fc16b4808fa88a0781693d
- story that removed it: [#153194965](https://www.pivotaltracker.com/n/projects/1488988/stories/153194965)
> don't try to copy the .bbl directory

- dockerfiles/cf-deployment-concourse-tasks/Dockerfile
This PR adds the log-cache-cli CF plugin to the Dockerfile so that it can be used with CATs.
> Add log-cache-cli to Dockerfile

- dockerfiles/cf-deployment-concourse-tasks/Dockerfile
This allows users of cf-deployment-concourse-tasks to use encrypted git repositories to store state. Support for git-crypt is built in to the latest version of concourse/git-resource.
cc @jamesjoshuahill
> Add git-crypt to CI image

- bosh-deploy/task.yml
A [question in slack](https://cloudfoundry.slack.com/archives/C2U7KA7M4/p1531247320000385) brought it to my attention
that this description wasn't,
perhaps,
updated when the option to not use a vars store was added.
Here's the code for the behavior this change describes:
https://github.com/cloudfoundry/cf-deployment-concourse-tasks/blob/afc0d171fd44543a138133b909e5375b4db8f44a/shared-functions#L103-L107
I've only corrected this here, other tasks with similar parameters
may have the same issue.
> Correct VARS_STORE_FILE description

- bosh-deploy-with-created-release/task.yml
- bosh-deploy-with-updated-release-submodule/task.yml
- bosh-deploy/task.yml
- shared-functions
Modified the shared-functions to use a given password and not credhub
Changes to be less diego specific
> set use_single_app_instance config through env var

- update-integration-configs/task
The Diego team has an environment that includes both windows2012 and windows2016 cells. When we upgrade our integration configs, we actually want to update two WATs configs, one for each kind of windows cell. Since the interface of the task only allows the update of a single WATs config, we run the task an extra time and that one only updates the WATs 2016 config. That task was getting an error because this validation assumes that you have either a CATs or RATs config also being updated.
> Update-integration-configs should not fail if only a wats config is provided

- update-integration-configs/task
We created a PR in cf-deployment(https://github.com/cloudfoundry/cf-deployment/pull/580) and cf-acceptance tests(https://github.com/cloudfoundry/cf-acceptance-tests/pull/321) to add a UAA credhub_admin_client that has the proper credhub permissions for creating and reading credentials in cf-acceptance tests. This just updates the config to use the credhub_admin_client instead of the cc_service_key_client.   
Signed-off-by: Anna Thornton <athornton@pivotal.io>
> Update config task to use credhub_admin_client_secret

- bosh-deploy-with-created-release/task
- bosh-deploy-with-created-release/task.yml
- shared-functions
[#159780275]
Signed-off-by: Slawek Ligus <sligus@pivotal.io>
We had the need to recreate/repave our deployment. This allows for optional bosh deploy args when deploying.
> Extend bosh deploy by optional arguments

- shared-functions
In special circumstances, such as when using git-crypt and running this task in a [older version of concourse](https://github.com/concourse/git-resource/commit/648fd8794f5c874e2ef44a92cb87cd29c51d4e5f), git status can fail. 
Even though we have `-e`, when we wrap commands in `if` statements like this, the expression be evaluated but no checking will be made on the exit code.
Extracting the output of `git status` to a variable will ensure we are testing not only the output, but also exiting when it fails.
> Extract `git status` to a variable

- run-errand/task
- run-errand/task.yml
Added support to allow extra parameters to be added in the future.
Paired with @aclevername
> Add option to configure keep-alive when running errand

- dockerfiles/cf-deployment-concourse-tasks/Dockerfile
The cf-deployment-concourse-tasks docker container is useful as a container to operate your environment by mounting the bbl-state in and evaluating it. However recently you're unable to bosh ssh into any instances using the most recent version as `nc` is not installed. By installing the `netcat-openbsd` (_see https://github.com/cloudfoundry/bosh-cli/issues/328#issuecomment-344052164_) package you're able to bosh ssh into vms.
> Added netcat-openbsd to the base container

- bbl-up/task
- bbl-up/task.yml
This change add more debug output to `bbl-up` task.
I love to use this tool for deploying CloudFoundry. However, as an engineer, I definitely need to understand what is going on when I trigger the job. Without a debug output I'm acting like a blind. Moreover, Concourse destroys containers after successful deployment, so I will not be able to troubleshoot anything in future, because `bbl-up.txt` will gone within container.
n/a
n/a
> More debug output

- bbl-up/task
Hi!
This is a quick follow-up for #84 
I just realized that it not working as expected, because `tee` aways has successful exit status, so pipeline never fails.
This fix is for catching a real status from `bbl` call.
Sorry for not foreseeing this issue before.
> More debug

- run-errand/task
- run-errand/task.yml
This PR adds an `INSTANCE` parameter to the `run-errand` task. It is required to allow CI jobs to disambiguate between different-configured copies of the same errand job within a deployment. For the Diego Persistence team, we test our `nfsbrokerpush` errand with different configuration for the backing store used by the NFS broker application. This change allows us to specify which instance of the errand should be run.
[#161974894](https://www.pivotaltracker.com/story/show/161974894)
Updated Tasks:
* `run-errand`
* Added parameterized support for specifying the instance that should be used to run an errand.
@paulcwarren @juluan-hj
> Add instance flag to run-errand task

- README.md
- bosh-delete-deployment/task
- bosh-delete-deployment/task.yml
Its a task to delete all bosh deployments, so that we can delete the deployments without needing to specify the deployment names.
We are adding pipelines to bbl-up our existing environments and bbl-down any environments that we might someday need to destroy. As part of destroying these environments, we may have to delete the bosh deployments and we may not know the names of those bosh deployments. We created this script to do just that and thought it might be of use here!
* bosh-delete-all-deployments - delete all bosh deployments
@genevieve #pcf-windows and #garden-windows
> Add task to delete all bosh deployments

- bbl-destroy/task
- bbl-destroy/task.yml
- bbl-up/task
- bbl-up/task.yml
This PR updates the `bbl-up` and `bbl-destroy` tasks to create tarballs from the bbl-state directory instead of attempting to commit them to a git repository. This allows the tarball to be uploaded to S3 or GCS by a subsequent `put` step. This is controlled by an optional `STORE_BBL_STATE_AS_TARBALL` parameter.
This change is somewhat, but not entirely, related to the request made in this issue: https://github.com/cloudfoundry/cf-deployment-concourse-tasks/issues/88
The `bbl-up` and `bbl-destroy` tasks can now create tarballs from the bbl-state directory instead of attempting to commit them to a git repository. This allows the tarball to be uploaded to S3 or GCS by a subsequent `put` step. This is controlled by an optional `STORE_BBL_STATE_AS_TARBALL` parameter.
> Add ability to store bbl-state in S3/GCS as a tarball

- bosh-delete-deployment/task
When deleting all bosh deployments, we reference the force_flag but it is not set in that function.
_Describe the change and why it's needed._
_Include any links to other PRs, stories, slack discussions, etc... that will help establish context._
_Something brief that conveys the change and is written with the component author audience in mind._
> Resolve force_flag: unbound variable error

- bbl-up/task
- bbl-up/task.yml
This change deletes Terraform plugins from the bbl state directory in the bbl-up task before pushing the state to GitHub or tarring and uploading it to S3/GCS/etc.
These plugin files are very large (the GCP one is around 50 MB), and bbl will re-download them as needed using `terraform init` before every operation, so it's not necessary to keep them on disk.
There was some discussion between us over whether this new behavior should be default or not. We introduced a new parameter, `DELETE_TERRAFORM_PLUGINS`, to the bbl-up task to control this new behavior. This is currently defaulting to true but we are open to changing it to default false as well.
This PR came out of an in-person discussion with @vitreuz and @acosta11.
(my pair thinks this is a breaking change but I don't)
_Delete …
> Delete Terraform plugins before pushing bbl state

- bosh-deploy/task.yml
Looks like the task script is happy for this directory to be empty, yet the task will fail if it is not provided as an input. This is not so convenient for users who do not have any vars files to provide. Thus, make it an optional input.
https://cloudfoundry.slack.com/archives/C0FAEKGUQ/p1572475327009500
vars-files input is now optional on bosh-deploy task
@tylerschultz
> Make vars-files input optional on bosh-deploy task

- bosh-deploy-with-created-release/task.yml
- bosh-deploy-with-updated-release-submodule/task.yml
- bosh-deploy/task.yml
- bosh-upload-stemcells/task.yml
- open-asgs-for-bosh-instance-group/task.yml
- run-errand/task.yml
- set-feature-flags/task.yml
- shared-functions
- update-integration-configs/task.yml
This PR adds a new `toolsmiths-env` input to many of the tasks relying on bbl state (specifically, to tasks which do not run bbl commands other than `print-env` and which are not involved with cleaning up an environment. The `bbl-state` input is now optional, although the tasks will error if neither input is provided. When the `toolsmiths-env` input is provided, the new `--file` flag will be provided to `bbl print-env`, which will read desired environment variables from the Toolsmiths environments app metadata file.
This is necessary for users of Toolsmiths cf-deployment environments to be able to use cf-deployment-concourse-tasks, since the Toolsmiths environments app does not provide users with a full bbl state.
This depends on [this …
> Can use toolsmiths-env metadata

- shared-functions
Fixes the metadata code for toolsmiths-env added in a previous PR.
_Include any links to other PRs, stories, slack discussions, etc... that will help establish context._
The issue is that some functions were still looking at the bbl-state and not toolsmiths-env, so this PR adds code to resolve this issue raised by: 
[this Slack interrupt](https://pivotal.slack.com/archives/C0563B53F/p1574727529363200)
[which opened this story](https://www.pivotaltracker.com/story/show/169967286)
To fix: [this PR](https://github.com/cloudfoundry/cf-deployment-concourse-tasks/commit/1f69f207f00fa48d267f51d45d3c9b38eca3a771)
Fixes bug in allowing users to specify Toolsmiths' metadata instead of bbl state when targeting environments.
cc @nhsieh @bbtong @cloudfoundry/pcf-toolsmiths
> Fixes metadata capability for toolsmiths-env

- shared-functions
Signed-off-by: Rowan Jacobs <rojacobs@pivotal.io>
Fixes the path to Toolsmiths environment metadata.
Related to PR #102 
Fixes the path to Toolsmiths environment metadata.
cc @bbtong
> Fix toolsmiths metadata path

- bosh-deploy-with-created-release/task.yml
- bosh-deploy-with-updated-release-submodule/task.yml
- bosh-deploy/task.yml
- open-asgs-for-bosh-instance-group/task.yml
- set-feature-flags/task.yml
- shared-functions
Co-authored-by: Bruce Ricard <bricard@pivotal.io>
When using a toolsmiths environment, the SYSTEM_DOMAIN is dynamically
fetched from the metadata. It cannot be passed as a parameter in the
pipeline configuration.
https://www.pivotaltracker.com/story/show/169068487
The error message is slightly different now. Not sure if that counts as a breaking change.
Tasks can be used with toolsmiths Cf-Deployment environments
We are technically blocked, but are using our fork in the meantime.
@bruce-ricard 
#networking in slack
> feature: set SYSTEM_DOMAIN variable for toolsmiths

- set-feature-flags/task
The current SYSTEM_DOMAIN check runs before it can be set by `setup_bosh_env_vars`, which causes it to fail if the value is being read from an environment metadata file.
Fix a bug in the set-feature-flag task introduced in the last release where it would fail if used with a toolsmiths environment.
> Fix issue with set-feature-flags task

- bosh-cleanup/task.yml
- bosh-delete-deployment/task.yml
- bosh-deploy-with-created-release/task.yml
- bosh-deploy-with-updated-release-submodule/task.yml
- bosh-deploy/task.yml
- bosh-upload-stemcells/task.yml
- open-asgs-for-bosh-instance-group/task.yml
- run-errand/task.yml
- set-feature-flags/task.yml
- update-integration-configs/task.yml
Describe how bbl-state input and BBL_STATE_DIR params interact with toolsmiths-env input
[#169967477]
This change makes the documentation for tasks that take `toolsmiths-env` as input less confusing. Specifically, there is a note under the `BBL_STATE_DIR` param saying that if `toolsmiths-env` is specified as an input, `BBL_STATE_DIR` will be ignored.
https://www.pivotaltracker.com/story/show/169967477
Improve docs for tasks that take toolsmiths-env argument
@cloudfoundry/pcf-toolsmiths
> Improve docs for tasks that take toolsmiths-env argument

- update-integration-configs/task
- update-integration-configs/task.yml
CATS has the option to test private docker registries, this PR adds that support to update-integration-configs task so that the credentials doesn't have to get committed to repositories if it's public. 
Add support for populating integration-configs with private docker registries
> Add private docker registry support to update-intergration-configs task

- bosh-deploy-with-created-release/task
- `yq` returns `null` not empty when `name` or `final_name` is not found
Signed-off-by: David McClure <dmcclure@vmware.com>
Our builds began failing with this error after updating to a recent version of this repo:
```
+ bosh -n interpolate -v system_domain=ci-lite.routing.cf-app.com -o ops-files/use-compiled-releases.yml -o ops-files/bosh-lite.yml -o ops-files/use-postgres.yml -o ops-files/routing-acceptance-tests.yml -o ops-files/routing-smoke-tests.yml -o ops-files/add-lb-ca-cert.yml -o create-provided-release.yml cf-deployment/cf-deployment.yml
Error 'operation [0] in create-provided-release.yml failed': Expected to find exactly one matching array item for path '/releases/name=null' but found 0
```
Fixes regression introduced in this commit: …
> Fix release_name bosh-deploy-with-created-release

- bbl-up/task
Co-authored-by: Peter Chen <peterch@vmware.com>
Making the world a better place
A recent commit introduced a pipe chain with a yq in it and our job failed with "yq: command not found" but kept running since it was followed by a pipe.
@peterhaochen47
> ENH: fast fail in pipe chains

- bbl-up/task
A previous PR introduced the `pipefail` option to the `bbl-up` task. However, the formatting of that change does not work on linux machines, since linux interprets anything after the shebang as one argument (see https://unix.stackexchange.com/questions/533415/invalid-option-name-error-with-shebang-bin-bash-o-pipefail-in-script). 
This is a simple change to pull the `pipefail` option into a newline so it gets parsed correctly.
Previous PR: https://github.com/cloudfoundry/cf-deployment-concourse-tasks/pull/116
*but worth calling out that this had broken our pipeline, and may have done the same for others.
@sweinstein22
> Move pipefail option in bbl-up/task script

- bbl-destroy/task.yml
- bbl-up/task.yml
- bosh-cleanup/task.yml
- bosh-delete-deployment/task.yml
- bosh-deploy-with-created-release/task.yml
- bosh-deploy-with-updated-release-submodule/task.yml
- bosh-deploy/task.yml
- bosh-upload-stemcells/task.yml
- collect-ops-files/task.yml
- open-asgs-for-bosh-instance-group/task.yml
- run-cats/task.yml
- run-errand/task.yml
- set-feature-flags/task.yml
- update-integration-configs/task.yml
The registry-image resource was introduced more than two years ago as a drop-in replace for the docker-image resource. It's less resource-intense, faster, and doesn't rely on spawning a Docker daemon.
- https://github.com/concourse/registry-image-resource
Replace docker-image with registry-image resource.
N/A.
> Replace docker-image with registry-image resource

- dockerfiles/cf-deployment-concourse-tasks/Dockerfile
The current Ginkgo install command doesn't work anymore. This PR conflicts with https://github.com/cloudfoundry/cf-deployment-concourse-tasks/pull/127 (install Ginkgo v2). The cf-performance tests have not yet been migrated to v2, however.
The current install fails with:
```
go: warning: "github.com/onsi/ginkgo/..." matched no packages
```
I would propose to replace this with:
```
go: downloading golang.org/x/tools v0.0.0-20201224043029-2b0845dc783e
go: downloading github.com/nxadm/tail v1.4.8
go: downloading golang.org/x/sys v0.0.0-20210112080510-489259a85091
go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: downloading github.com/fsnotify/fsnotify v1.4.9
Ginkgo Version 1.16.5
```
Fix for regression: Ginkgo v1 CLI is available again.
> Fix Ginkgo v1 install command

- run-cats/task
- run-cats/task.yml
This PR updates the flags specified in the run-cats task to use the new versions of the Ginkgo v2 CLI and updates the slow spec threshold to be a Golang time duration instead of a number of seconds. A new `TIMEOUT` parameter has been introduced to allow CI jobs to change the default Ginkgo timeout, which is now applied to the entire test suite run, instead of each individual test suite. It defaults to 2 hours, instead of the Ginkgo default of 1 hour.
Related to https://github.com/cloudfoundry/cf-acceptance-tests/pull/543
The Ginkgo CLI flags specified in the run-cats task have been updated to use the new versions of v2. The slow spec threshold has been updated to be a Golang time duration instead of a number of seconds. A new `TIMEOUT` parameter has been introduced to allow CI jobs to …
> Update run-cats to use the new Ginkgo v2 CLI flags

- bbl-destroy/task
- bbl-up/task
Fixes a small issue in the `bbl-up` task which causes it to fail to print the nameservers for the created DNS zone when deploying on AWS.
For some odd reason, `bbl` gives this output different names for aws and gcp. For the latter it's named [system_domain_dns_servers](https://github.com/cloudfoundry/bosh-bootloader/blob/b9b92c7b41fca198b59d19e1848292838f7d9e9d/commands/gcp_lbs.go#L56), and for the former it's [env_dns_zone_name_servers](https://github.com/cloudfoundry/bosh-bootloader/blob/b9b92c7b41fca198b59d19e1848292838f7d9e9d/commands/aws_lbs.go#L60). As a result, this is the build output you currently get if you're running on aws (and presumably any other IaaS other than gcp):
```
Please configure DNS with the following servers:
+ bbl outputs
+ yq .system_domain_dns_servers -y
+ cut …
```
> improve output for bbl up/destroy tasks

- dockerfiles/cf-deployment-concourse-tasks/Dockerfile
~This PR bumps the version of the Ginkgo CLI included in the docker image to v2 to match the version used in CATs.~
Edit: This PR removes the ginkgo CLI from the docker image, as the version of the CLI must match the local Ginkgo library version in any given project. Therefore, we need to push the responsibility onto project owners to vendor and use the tool appropriately.
* Related to https://github.com/cloudfoundry/cf-acceptance-tests/pull/543
* https://github.com/onsi/ginkgo/releases/tag/v2.3.1
~This PR bumps the version of the Ginkgo CLI included in the docker image to v2 to match the version used in CATs.~
This PR removes the ginkgo CLI from the docker image.
@ctlong
> Remove the Ginkgo CLI

- run-cats/task
- run-cats/task.yml
* Removes `--slow-spec-threshold` flag.
* Removes SLOW_SPEC_THRESHOLD param from task.
* Gets rid of annoying warning message at the end of CATs runs.
* Prepares us for the flag being ripped out at any point
Warning message from ginkgo when this flag is used:
```
You're using deprecated Ginkgo functionality:
=============================================
--slow-spec-threshold is deprecated --slow-spec-threshold has been deprecated and will be removed in a future version of Ginkgo.  This feature has proved to be more noisy than useful.  You can use --poll-progress-after, instead, to get more actionable feedback about potentially slow specs and understand where they might be getting stuck.
```
Remove slow spec threshold option from run-cats task, as it's deprecated by ginkgo.
None.
> Remove deprecated ginkgo flag from CATs run

- bbl-destroy/task
Removes `--skip-if-missing` flag, which was removed from the `bbl` CLI.
* [bbl commit removing it](https://github.com/cloudfoundry/bosh-bootloader/commit/0e2b566dee7ded01069adce34f00db9c40ee20e1)
None
> Update bbl-destroy task

- dockerfiles/cf-deployment-concourse-tasks/Dockerfile
* Write each complicated RUN step as a mini bash script. I think it's clearer to read.
* Bump git-crypt to latest.
* Install binaries where possible.
None
None
> Fix: reformat dockerfile and bump git-crypt

- ci/tasks/bump-cf-d-ct-docker-image/task
- ci/tasks/update-cf-d-ct-dockerfile-versions/task
Update the git user and mail configuration for the "cf-deployment-concourse-tasks" CI pipeline.
Tasks are only used for cf-deployment-concourse-tasks CI pipeline: https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment-concourse-tasks
No update necessary, the two changed tasks are not documented in the README.
Not relevant for release notes.
> Migrate git user/mail configuration to ARD WG

- bosh-deploy-with-created-release/task.yml
- bosh-deploy-with-updated-release-submodule/task.yml
- bosh-deploy/task.yml
- shared-functions
This PR to the `cf-deployment-concourse-tasks` updates the `uptimer` config writing process to include the TCP availability measurement changes introduced to `uptimer` in https://github.com/cloudfoundry/uptimer/pull/27. These changes allow consumers of `cf-deployment-concourse-tasks` to configure any of the three `bosh-deploy` tasks to measure TCP availability to an app on the foundation with `uptimer` during a deployment. This change also automatically calculates the TCP domain of a Toolsmiths env, if provided, instead of explicitly requiring the TCP domain to be configured at the concourse task param level.
These changes are useful for testing the availability of TCP when we are performing deployments that cause downtime to the TCP router.
Measuring TCP availability correctly also …
> Add uptimer tcp availability config to bosh deploy tasks

- bbl-up/task
Calls `terraform init` in `bbl-up` task if `DELETE_TERRAFORM_PLUGINS` is set to `false`. This should ensure that certain bbl commands, that require the correct plugins, work
https://github.com/cloudfoundry/bosh-bootloader/issues/560
Fix issues related to running certain `bbl` commands by running `terraform init` beforehand.
None
> Fix: bbl-up task

- dockerfiles/cf-deployment-concourse-tasks/Dockerfile
Recent bbl releases use a different postfix for the linux binary.
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment-concourse-tasks/jobs/build-docker-image/builds/137
N/A
None
> Fix: bbl download link in dockerfile

- shared-functions
Update bosh_interpolate to pull release version info from the provided tarball to avoid bosh manifest errors
When providing a release tarball to  bosh-deploy-with-created-release, the resultant manifest doesn't include a `version` directive for the release, and bosh fails to validate the manifest.
If you're able to see it, this breaks the [windows-roofts pipeline](https://ci.funtime.lol/teams/garden-windows/pipelines/windows-rootfs/jobs/offline-smoke-tests/builds/18), and we're trying to consolidate onto common tasks instead of previously used release-specific tasks that didn't suffer from this issue. 
This is a much smaller fix in scope than #139, but if that is deemed preferable, this one is likely not needed.
Fixes an issue with `bosh-deploy-with-created-release` where passing a …
> Update bosh-deploy-with-created-release to build a valid manifest when specifying a release tarball

- shared-functions
This allows for compatibility with other pooled environment providers
Toolsmiths provides two ways to fetch the name of the an environment:
1. The `name` file, which is currently used
2. The `metadata` file, which is a json file with the environment name saved in the top-level `name` field.
This change switches to the second implementation, as other pooled environment providers have maintained the same `metadata` file schema for compatibility.
N/A
Use `metadata` file instead of `name` file to fetch environment name
> Use metadata file instead of name file

- dockerfiles/cf-deployment-concourse-tasks/Dockerfile
credhub-cli repo started publishing darwin/arm64 binaries, and have correspondingly changed their release binary names.
We probably want the linux/amd64 one, it's what we were using before for this image.
https://github.com/cloudfoundry/credhub-cli/releases/tag/2.9.20
None
> fix(dockerfile): use new credhub-cli download URL

- dockerfiles/cf-deployment-concourse-tasks/Dockerfile
Fix missing "\" in multiline command, was introduced with https://github.com/cloudfoundry/cf-deployment-concourse-tasks/pull/162
https://github.com/cloudfoundry/cf-deployment-concourse-tasks/pull/162
N/A
> Fix missing \ for multiline command

- dockerfiles/cf-deployment-concourse-tasks/Dockerfile
The url var assignment was missing a semi-colon to delimit the command.
* https://github.com/cloudfoundry/cf-deployment-concourse-tasks/pull/162
* https://github.com/cloudfoundry/cf-deployment-concourse-tasks/pull/163
None
> Fix(dockerfile): typo in downloading credhub CLI

- ci/pipeline.yml
- ci/tasks/update-cf-d-ct-dockerfile-versions/task
- ci/tasks/update-cf-d-ct-dockerfile-versions/task.yml
- dockerfiles/cf-deployment-concourse-tasks/Dockerfile
Upgrades the cf-d-c-t docker image to have Debian bullseye as the base of the image.
Included some refactors and updates that I think should be relatively minor:
- No longer include the bbl repo at `var/repos/bosh-bootloader`.
- Remove duplicate package installations.
- Remove packages that don't appear to be needed for any specific reason.
- Use ruby 2.7.7 instead of ruby 2.5.4.
Closes #165.
None
> Feat(dockerfile): Upgrade to bullseye

- bbl-up/task
Fix failures in bbl-up task in CI by using the correct flags for the new `yq` CLI.
- https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/update-releases/jobs/update-stemcell-minor/builds/21
- #167 
N/A
> Fix(bbl-up): Use correct flags for new `yq` CLI

- bosh-deploy/task
- bosh-deploy/task.yml
Add an option to the "bosh-deploy" task to skip the stemcell upload. This is useful in scenarios like the FIPS stemcell validation where the stemcell must be downloaded from a protected storage.
Will be used in FIPS stemcell validation pipeline: https://github.com/cloudfoundry/cf-deployment/pull/1135
Change does not introduce regressions (i.e. default behaviour stays the same).
Docu is in `task.yml`.
Add option `SKIP_STEMCELL_UPLOAD` to the `bosh-deploy` task.
> Option for "bosh-deploy" task to skip stemcell upload

- shared-functions
[Fixes #178]
Fixes an issue where SYSTEM_DOMAIN is sometimes incorrectly extracted from "toolsmiths-env" input. 
n/a
_Something brief that conveys the change and is written with the component author audience in mind._
> fix: SYSTEM_DOMAIN incorrectly extracted from toolsmiths-env

- bosh-deploy-with-created-release/task.yml
- bosh-deploy-with-updated-release-submodule/task.yml
- bosh-deploy/task.yml
- shared-functions
After adding this new measurement, our CI is failing this measurement because the default value of 0 is too aggresssive for cf-deployment when routing-release is getting updated. This PR adds the ablity to set app_stats when needed.
Context: cloudfoundry/uptimer#115
Add ability for setting app_stats
> Add ability for setting app_stats

- dockerfiles/cf-deployment-concourse-tasks/Dockerfile
Assets name for the log-cache-cf-plugin was changed. As a result, the build-docker-image job is failing and this change need to be propagated....
_Describe the change and why it's needed._
Fixe the downloadable asset name for log-cache-cf-plugin used in  Dockefile.
_Include any links to other PRs, stories, slack discussions, etc... that will help establish context._
https://github.com/cloudfoundry/log-cache-cli/pull/257
N/A
> Fix log cache plugin asset name

- shared-functions
The upload_stemcell function checks if the BOSH_LITE variable is true before checking anything else. Fixes an edge case where toolsmiths-env exists but is a BOSH_LITE.
None
None
> fix(shared-functions): Check for BOSH_LITE first in upload_stemcell function

- bbl-up/task
Small enhancement for "Azure" infrastructures. Print the list of DNS name servers if it is contained in `bbl outputs`.
https://github.com/cloudfoundry/cloud_controller_ng/pull/4397
The `bbl-up` task now prints the DNS name servers for Azure bbl installations (if available in `bbl outputs`).
> Add "Azure" to DNS advisory check
